"""Add dev, company, freebie models

Revision ID: 5d64e302686b
Revises: 444498231822
Create Date: 2025-05-30 05:33:05.364393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d64e302686b'
down_revision: Union[str, None] = '444498231822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('devs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('freebies', 'item_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('freebies', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freebies', sa.Column('value', sa.INTEGER(), nullable=True))
    op.alter_column('freebies', 'item_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
